version: '3.8'

services:
  # --- BACKEND SERVICE ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: node_backend
    expose:
      - "3000"
    # environment:
    #   - PORT=${APP_PORT}
    #   - DB_HOST=${DB_HOST}
    #   - DB_PORT=${DB_PORT}
    #   # 👇 Translating your Terraform variables for app.js
    #   - DB_USER=${var.db_username}
    #   - DB_PASSWORD=${var.db_password}
    #   - DB_NAME=${var.db_name}
    networks:
      - app-network
    restart: always

  # --- FRONTEND SERVICE ---
  frontend:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: nginx_frontend
    ports:
      - "80:80" # Exposes Nginx to your host machine / browser
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

# --- NETWORKS ---
networks:
  app-network:
    driver: bridge