version: '3.8'

services:
  backend:
    image: spygram/backend:${BACKEND_VERSION:-latest}
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - app-network
    environment:
      - PORT=${APP_PORT:-3000}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT:-5432}
    restart: always

  frontend:
    image: spygram/frontend:${FRONTEND_VERSION:-latest}
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

networks:
  app-network:
    driver: bridge