pipeline {
    agent any

    
    environment {
        // Define your Docker Hub repository and image tags
        IMAGE_REPO = 'spygram' // Replace with your actual Docker Hub username/org
        IMAGE_TAG  = "0.0.${env.BUILD_NUMBER}"    // Uses the Jenkins build number as the unique tag
        //API_URL = "http://100.29.11.212:8000"
    }

    stages {

           

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub_credential', 
                                                  usernameVariable: 'USERNAME', 
                                                  passwordVariable: 'PASSWORD')]) {
                    sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                    echo 'Logged in successfully'
                }
            }
        }

        stage('Docker build') {
            steps {
                echo 'Building frontend Docker image...'
                // Builds and tags the image using your variables
                sh "docker build -t ${IMAGE_REPO}/frontend:${IMAGE_TAG} ./public"
                sh "docker push ${IMAGE_REPO}/frontend:${IMAGE_TAG}"
                sh "docker push ${IMAGE_REPO}/frontend:latest"
            }            
        }
    }

    post {
        success {
            echo 'Frontend build and push completed successfully!'
        }
        failure {
            echo 'Frontend pipeline failed. Check logs.'
        }
    }
}